// Протокол runner ↔ control plane (см. design и api-contract изменения
// define-rivet-architecture). Соединение всегда исходящее от runner'а.
// Доставка at-least-once: каждое сообщение несёт msg_id, приём подтверждается
// Ack, дедупликация на стороне получателя.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: pkg/protocol/rivet.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageResult_Stage int32

const (
	StageResult_STAGE_UNSPECIFIED StageResult_Stage = 0
	StageResult_CODING            StageResult_Stage = 1 // реализация завершена (ok) или невосстановимая ошибка (!ok)
	StageResult_TESTING           StageResult_Stage = 2 // проверки прошли/упали
	StageResult_REVIEW            StageResult_Stage = 3 // вердикт независимого ревьюера
	StageResult_FIXING            StageResult_Stage = 4 // исправление готово
)

// Enum value maps for StageResult_Stage.
var (
	StageResult_Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "CODING",
		2: "TESTING",
		3: "REVIEW",
		4: "FIXING",
	}
	StageResult_Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"CODING":            1,
		"TESTING":           2,
		"REVIEW":            3,
		"FIXING":            4,
	}
)

func (x StageResult_Stage) Enum() *StageResult_Stage {
	p := new(StageResult_Stage)
	*p = x
	return p
}

func (x StageResult_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageResult_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_rivet_proto_enumTypes[0].Descriptor()
}

func (StageResult_Stage) Type() protoreflect.EnumType {
	return &file_pkg_protocol_rivet_proto_enumTypes[0]
}

func (x StageResult_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageResult_Stage.Descriptor instead.
func (StageResult_Stage) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{8, 0}
}

type DeployResult_Stage int32

const (
	DeployResult_STAGE_UNSPECIFIED DeployResult_Stage = 0
	DeployResult_DEPLOY            DeployResult_Stage = 1
	DeployResult_VERIFY            DeployResult_Stage = 2
)

// Enum value maps for DeployResult_Stage.
var (
	DeployResult_Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "DEPLOY",
		2: "VERIFY",
	}
	DeployResult_Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"DEPLOY":            1,
		"VERIFY":            2,
	}
)

func (x DeployResult_Stage) Enum() *DeployResult_Stage {
	p := new(DeployResult_Stage)
	*p = x
	return p
}

func (x DeployResult_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployResult_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_rivet_proto_enumTypes[1].Descriptor()
}

func (DeployResult_Stage) Type() protoreflect.EnumType {
	return &file_pkg_protocol_rivet_proto_enumTypes[1]
}

func (x DeployResult_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployResult_Stage.Descriptor instead.
func (DeployResult_Stage) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{20, 0}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunnerId        string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Agent           string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Host            string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Capabilities    []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Адаптер подключения агента (claude-code, wrap) и глубина данных,
	// которую он даёт: full | partial | minimal (спека agent-integration
	// «Уровни глубины данных»). Сессии runner'а создаются с этой глубиной.
	Adapter string `protobuf:"bytes,7,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Depth   string `protobuf:"bytes,8,opt,name=depth,proto3" json:"depth,omitempty"`
	// Поддерживает ли адаптер обратный канал контекста (PlaneMsg.Context):
	// нативный адаптер доводит контекст до агента, обёртка — нет, и таким
	// runner'ам control plane контекст не шлёт (спека agent-integration
	// «Обратный канал контекста»).
	ContextChannel bool `protobuf:"varint,9,opt,name=context_channel,json=contextChannel,proto3" json:"context_channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *RegisterRequest) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *RegisterRequest) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

func (x *RegisterRequest) GetContextChannel() bool {
	if x != nil {
		return x.ContextChannel
	}
	return false
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Несовместимая версия протокола — понятная ошибка, не разрыв соединения.
	Accepted           bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message            string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalS int32  `protobuf:"varint,3,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalS() int32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

type RunnerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // uuid, база дедупликации и Ack
	// Types that are valid to be assigned to Kind:
	//
	//	*RunnerMsg_Hello
	//	*RunnerMsg_Heartbeat
	//	*RunnerMsg_Event
	//	*RunnerMsg_Transcript
	//	*RunnerMsg_Usage
	//	*RunnerMsg_StageResult
	//	*RunnerMsg_Blocked
	//	*RunnerMsg_DeployResult
	Kind          isRunnerMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerMsg) Reset() {
	*x = RunnerMsg{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerMsg) ProtoMessage() {}

func (x *RunnerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerMsg.ProtoReflect.Descriptor instead.
func (*RunnerMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{2}
}

func (x *RunnerMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RunnerMsg) GetKind() isRunnerMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunnerMsg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *RunnerMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunnerMsg) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunnerMsg) GetTranscript() *TranscriptChunk {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *RunnerMsg) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *RunnerMsg) GetStageResult() *StageResult {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_StageResult); ok {
			return x.StageResult
		}
	}
	return nil
}

func (x *RunnerMsg) GetBlocked() *BlockedQuestion {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Blocked); ok {
			return x.Blocked
		}
	}
	return nil
}

func (x *RunnerMsg) GetDeployResult() *DeployResult {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_DeployResult); ok {
			return x.DeployResult
		}
	}
	return nil
}

type isRunnerMsg_Kind interface {
	isRunnerMsg_Kind()
}

type RunnerMsg_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type RunnerMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type RunnerMsg_Event struct {
	Event *AgentEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type RunnerMsg_Transcript struct {
	Transcript *TranscriptChunk `protobuf:"bytes,5,opt,name=transcript,proto3,oneof"`
}

type RunnerMsg_Usage struct {
	Usage *Usage `protobuf:"bytes,6,opt,name=usage,proto3,oneof"`
}

type RunnerMsg_StageResult struct {
	StageResult *StageResult `protobuf:"bytes,7,opt,name=stage_result,json=stageResult,proto3,oneof"`
}

type RunnerMsg_Blocked struct {
	Blocked *BlockedQuestion `protobuf:"bytes,8,opt,name=blocked,proto3,oneof"`
}

type RunnerMsg_DeployResult struct {
	DeployResult *DeployResult `protobuf:"bytes,9,opt,name=deploy_result,json=deployResult,proto3,oneof"`
}

func (*RunnerMsg_Hello) isRunnerMsg_Kind() {}

func (*RunnerMsg_Heartbeat) isRunnerMsg_Kind() {}

func (*RunnerMsg_Event) isRunnerMsg_Kind() {}

func (*RunnerMsg_Transcript) isRunnerMsg_Kind() {}

func (*RunnerMsg_Usage) isRunnerMsg_Kind() {}

func (*RunnerMsg_StageResult) isRunnerMsg_Kind() {}

func (*RunnerMsg_Blocked) isRunnerMsg_Kind() {}

func (*RunnerMsg_DeployResult) isRunnerMsg_Kind() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отсутствие поля = заполненность контекста неизвестна (агент не отчитался).
	CtxPct        *int32 `protobuf:"varint,1,opt,name=ctx_pct,json=ctxPct,proto3,oneof" json:"ctx_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetCtxPct() int32 {
	if x != nil && x.CtxPct != nil {
		return *x.CtxPct
	}
	return 0
}

// AgentEvent — шаг агента для live-наблюдения (session.step).
// text — обязательное читаемое представление; структурированные поля
// заполняет адаптер полной глубины (спека agent-integration «Шаги сессии
// и затронутые файлы»).
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // сессия стадии из Assignment
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`                            // tool | stop | note; пусто — простой текстовый шаг
	Tool          string                 `protobuf:"bytes,5,opt,name=tool,proto3" json:"tool,omitempty"`                            // имя инструмента агента (kind=tool)
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`                        // краткий аргумент: команда, путь, шаблон
	Files         []string               `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`                          // затронутые файлы шага (пути от корня рабочей копии)
	Ok            bool                   `protobuf:"varint,8,opt,name=ok,proto3" json:"ok,omitempty"`                               // false — шаг завершился ошибкой
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{5}
}

func (x *AgentEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *AgentEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AgentEvent) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AgentEvent) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TranscriptChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // сессия стадии из Assignment; несовпадение — сообщение отбрасывается
	DeployId      string                 `protobuf:"bytes,5,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`    // вывод деплой-джобы: заполняется вместо task_id/session_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptChunk) Reset() {
	*x = TranscriptChunk{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptChunk) ProtoMessage() {}

func (x *TranscriptChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptChunk.ProtoReflect.Descriptor instead.
func (*TranscriptChunk) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{6}
}

func (x *TranscriptChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TranscriptChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TranscriptChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TranscriptChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptChunk) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

// Usage — отчёт о расходе за стадию. Отсутствие optional-поля означает
// «данных нет» (агент не отчитался маркером USAGE:), а не ноль.
type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // сессия стадии из Assignment
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TokensIn      *int64                 `protobuf:"varint,3,opt,name=tokens_in,json=tokensIn,proto3,oneof" json:"tokens_in,omitempty"`
	TokensOut     *int64                 `protobuf:"varint,4,opt,name=tokens_out,json=tokensOut,proto3,oneof" json:"tokens_out,omitempty"`
	CostUsd       *float64               `protobuf:"fixed64,5,opt,name=cost_usd,json=costUsd,proto3,oneof" json:"cost_usd,omitempty"`
	DurationS     int32                  `protobuf:"varint,6,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	CtxPct        *int32                 `protobuf:"varint,7,opt,name=ctx_pct,json=ctxPct,proto3,oneof" json:"ctx_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Usage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Usage) GetTokensIn() int64 {
	if x != nil && x.TokensIn != nil {
		return *x.TokensIn
	}
	return 0
}

func (x *Usage) GetTokensOut() int64 {
	if x != nil && x.TokensOut != nil {
		return *x.TokensOut
	}
	return 0
}

func (x *Usage) GetCostUsd() float64 {
	if x != nil && x.CostUsd != nil {
		return *x.CostUsd
	}
	return 0
}

func (x *Usage) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *Usage) GetCtxPct() int32 {
	if x != nil && x.CtxPct != nil {
		return *x.CtxPct
	}
	return 0
}

// StageResult — детерминированный итог этапа конвейера.
type StageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         StageResult_Stage      `protobuf:"varint,2,opt,name=stage,proto3,enum=rivet.v1.StageResult_Stage" json:"stage,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                           // вывод тестов, вердикт review, url PR
	PrUrl         string                 `protobuf:"bytes,5,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`                // для stage=CODING при создании PR
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`    // сессия стадии из Assignment
	PolicyHash    string                 `protobuf:"bytes,7,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"` // эхо Assignment.policy.hash: итог стадии привязан к версии
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageResult) Reset() {
	*x = StageResult{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageResult) ProtoMessage() {}

func (x *StageResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageResult.ProtoReflect.Descriptor instead.
func (*StageResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{8}
}

func (x *StageResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageResult) GetStage() StageResult_Stage {
	if x != nil {
		return x.Stage
	}
	return StageResult_STAGE_UNSPECIFIED
}

func (x *StageResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StageResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *StageResult) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *StageResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StageResult) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

// BlockedQuestion — агент не может продолжить без человека.
type BlockedQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // сессия стадии из Assignment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedQuestion) Reset() {
	*x = BlockedQuestion{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedQuestion) ProtoMessage() {}

func (x *BlockedQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedQuestion.ProtoReflect.Descriptor instead.
func (*BlockedQuestion) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedQuestion) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BlockedQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *BlockedQuestion) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PlaneMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PlaneMsg_Ack
	//	*PlaneMsg_Assign
	//	*PlaneMsg_Answer
	//	*PlaneMsg_Cancel
	//	*PlaneMsg_Pause
	//	*PlaneMsg_Deploy
	//	*PlaneMsg_Context
	Kind          isPlaneMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaneMsg) Reset() {
	*x = PlaneMsg{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneMsg) ProtoMessage() {}

func (x *PlaneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneMsg.ProtoReflect.Descriptor instead.
func (*PlaneMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{10}
}

func (x *PlaneMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PlaneMsg) GetKind() isPlaneMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PlaneMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *PlaneMsg) GetAssign() *Assignment {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *PlaneMsg) GetAnswer() *Answer {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *PlaneMsg) GetCancel() *CancelTask {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *PlaneMsg) GetPause() *PauseRunner {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *PlaneMsg) GetDeploy() *DeployJob {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Deploy); ok {
			return x.Deploy
		}
	}
	return nil
}

func (x *PlaneMsg) GetContext() *Context {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Context); ok {
			return x.Context
		}
	}
	return nil
}

type isPlaneMsg_Kind interface {
	isPlaneMsg_Kind()
}

type PlaneMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type PlaneMsg_Assign struct {
	Assign *Assignment `protobuf:"bytes,3,opt,name=assign,proto3,oneof"`
}

type PlaneMsg_Answer struct {
	Answer *Answer `protobuf:"bytes,4,opt,name=answer,proto3,oneof"`
}

type PlaneMsg_Cancel struct {
	Cancel *CancelTask `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type PlaneMsg_Pause struct {
	Pause *PauseRunner `protobuf:"bytes,6,opt,name=pause,proto3,oneof"`
}

type PlaneMsg_Deploy struct {
	Deploy *DeployJob `protobuf:"bytes,7,opt,name=deploy,proto3,oneof"`
}

type PlaneMsg_Context struct {
	Context *Context `protobuf:"bytes,8,opt,name=context,proto3,oneof"`
}

func (*PlaneMsg_Ack) isPlaneMsg_Kind() {}

func (*PlaneMsg_Assign) isPlaneMsg_Kind() {}

func (*PlaneMsg_Answer) isPlaneMsg_Kind() {}

func (*PlaneMsg_Cancel) isPlaneMsg_Kind() {}

func (*PlaneMsg_Pause) isPlaneMsg_Kind() {}

func (*PlaneMsg_Deploy) isPlaneMsg_Kind() {}

func (*PlaneMsg_Context) isPlaneMsg_Kind() {}

// Context — контекст работающему агенту от control plane (обратный канал):
// предупреждение о пересечении работ и т.п. Доставляется во время
// выполняющейся стадии, работу не прерывает и результат не отменяет.
// Отправляется только runner'ам, объявившим context_channel.
type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // сессия стадии из Assignment
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                            // вид контекста: overlap
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                            // готовое сообщение агенту
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{11}
}

func (x *Context) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Context) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Context) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Context) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedMsgId    string                 `protobuf:"bytes,1,opt,name=acked_msg_id,json=ackedMsgId,proto3" json:"acked_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetAckedMsgId() string {
	if x != nil {
		return x.AckedMsgId
	}
	return ""
}

// Assignment — задача этапу runner'а: кодирование, тесты, review или фикс.
type Assignment struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskId       string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNum      int64                  `protobuf:"varint,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	Stage        StageResult_Stage      `protobuf:"varint,3,opt,name=stage,proto3,enum=rivet.v1.StageResult_Stage" json:"stage,omitempty"`
	Title        string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description  string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Criteria     []string               `protobuf:"bytes,6,rep,name=criteria,proto3" json:"criteria,omitempty"`
	Repo         string                 `protobuf:"bytes,7,opt,name=repo,proto3" json:"repo,omitempty"`     // owner/name
	Branch       string                 `protobuf:"bytes,8,opt,name=branch,proto3" json:"branch,omitempty"` // agent/task-<num>
	Checks       []*Check               `protobuf:"bytes,9,rep,name=checks,proto3" json:"checks,omitempty"`
	ExtraContext string                 `protobuf:"bytes,10,opt,name=extra_context,json=extraContext,proto3" json:"extra_context,omitempty"` // замечания review при FIXING, diff при REVIEW и т.п.
	// Сессия стадии: runner повторяет session_id во всех сообщениях стадии
	// (Transcript, Usage, StageResult, Blocked); replay с чужим id отбрасывается.
	SessionId string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Репозиторий проекта: адрес клонирования без секрета и токен доступа.
	// Токен уезжает в git через askpass-хелпер, а не аргументом команды.
	// Пустой repo_url — старое поведение по RIVET_GIT_BASE (e2e-стенд).
	RepoUrl    string `protobuf:"bytes,12,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	GitToken   string `protobuf:"bytes,13,opt,name=git_token,json=gitToken,proto3" json:"git_token,omitempty"`
	BaseBranch string `protobuf:"bytes,14,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"` // базовая ветка проекта
	// Промпт пользователя (сессия доработки, add-user-sessions): при
	// непустом значении runner использует его как промпт агента вместо
	// сгенерированного промпта стадии.
	UserPrompt string `protobuf:"bytes,15,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
	// Действующая политика проекта на момент назначения (спека access-policy
	// «Доставка политик runner'ам»): runner применяет только её и не читает
	// политику из рабочей копии. Поле пустое, только если политику не удалось
	// прочитать: у проекта без своих версий действуют значения установки, и
	// хэш у них тоже есть.
	Policy        *Policy `protobuf:"bytes,16,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{13}
}

func (x *Assignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Assignment) GetTaskNum() int64 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *Assignment) GetStage() StageResult_Stage {
	if x != nil {
		return x.Stage
	}
	return StageResult_STAGE_UNSPECIFIED
}

func (x *Assignment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assignment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Assignment) GetCriteria() []string {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *Assignment) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Assignment) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Assignment) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *Assignment) GetExtraContext() string {
	if x != nil {
		return x.ExtraContext
	}
	return ""
}

func (x *Assignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Assignment) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Assignment) GetGitToken() string {
	if x != nil {
		return x.GitToken
	}
	return ""
}

func (x *Assignment) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

func (x *Assignment) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *Assignment) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// Policy — часть политики, которая что-то значит для агента стадии.
// Лимиты, бюджеты и авто-merge применяются на control plane и сюда не
// едут: обещать принуждение, которого у runner'а нет, не нужно.
type Policy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                                   // хэш версии действующей политики
	HumanReviewPaths []string               `protobuf:"bytes,2,rep,name=human_review_paths,json=humanReviewPaths,proto3" json:"human_review_paths,omitempty"` // пути, правки в которых требуют человека
	PolicyDir        string                 `protobuf:"bytes,3,opt,name=policy_dir,json=policyDir,proto3" json:"policy_dir,omitempty"`                        // каталог файлов политики (менять запрещено)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{14}
}

func (x *Policy) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Policy) GetHumanReviewPaths() []string {
	if x != nil {
		return x.HumanReviewPaths
	}
	return nil
}

func (x *Policy) GetPolicyDir() string {
	if x != nil {
		return x.PolicyDir
	}
	return ""
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{15}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{16}
}

func (x *Answer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Answer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{17}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PauseRunner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drain         bool                   `protobuf:"varint,1,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunner) Reset() {
	*x = PauseRunner{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunner) ProtoMessage() {}

func (x *PauseRunner) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunner.ProtoReflect.Descriptor instead.
func (*PauseRunner) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{18}
}

func (x *PauseRunner) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

// DeployJob — публикация окружения (спека backend/deployment): runner
// с capability deploy исполняет deploy_cmd/verify_cmd как shell-скрипт
// с переменными RIVET_REPO/VERSION/PREV_VERSION/ENV — по ssh на host или
// локально при пустом host. Откат — та же джоба с rollback=true и
// version=prev (деплой идемпотентен по версии).
type DeployJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	EnvName       string                 `protobuf:"bytes,2,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`       // owner/name
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // sha публикуемого коммита
	PrevVersion   string                 `protobuf:"bytes,5,opt,name=prev_version,json=prevVersion,proto3" json:"prev_version,omitempty"`
	Rollback      bool                   `protobuf:"varint,6,opt,name=rollback,proto3" json:"rollback,omitempty"`
	Host          string                 `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"` // [user@]hostname[:port]; пусто — локальное исполнение
	DeployCmd     string                 `protobuf:"bytes,8,opt,name=deploy_cmd,json=deployCmd,proto3" json:"deploy_cmd,omitempty"`
	VerifyCmd     string                 `protobuf:"bytes,9,opt,name=verify_cmd,json=verifyCmd,proto3" json:"verify_cmd,omitempty"`
	VerifyUrl     string                 `protobuf:"bytes,10,opt,name=verify_url,json=verifyUrl,proto3" json:"verify_url,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,11,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"` // дедлайн джобы на runner'е
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployJob) Reset() {
	*x = DeployJob{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployJob) ProtoMessage() {}

func (x *DeployJob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployJob.ProtoReflect.Descriptor instead.
func (*DeployJob) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{19}
}

func (x *DeployJob) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployJob) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *DeployJob) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeployJob) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeployJob) GetPrevVersion() string {
	if x != nil {
		return x.PrevVersion
	}
	return ""
}

func (x *DeployJob) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

func (x *DeployJob) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DeployJob) GetDeployCmd() string {
	if x != nil {
		return x.DeployCmd
	}
	return ""
}

func (x *DeployJob) GetVerifyCmd() string {
	if x != nil {
		return x.VerifyCmd
	}
	return ""
}

func (x *DeployJob) GetVerifyUrl() string {
	if x != nil {
		return x.VerifyUrl
	}
	return ""
}

func (x *DeployJob) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

// DeployResult — итог этапа публикации; чужой/stale deployment_id
// отбрасывается CAS-переходами статусов.
type DeployResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Stage         DeployResult_Stage     `protobuf:"varint,2,opt,name=stage,proto3,enum=rivet.v1.DeployResult_Stage" json:"stage,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`      // хвост вывода команд / причина
	Rollback      bool                   `protobuf:"varint,5,opt,name=rollback,proto3" json:"rollback,omitempty"` // эхо DeployJob.rollback: результат фазы отката
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResult) Reset() {
	*x = DeployResult{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResult) ProtoMessage() {}

func (x *DeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResult.ProtoReflect.Descriptor instead.
func (*DeployResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{20}
}

func (x *DeployResult) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployResult) GetStage() DeployResult_Stage {
	if x != nil {
		return x.Stage
	}
	return DeployResult_STAGE_UNSPECIFIED
}

func (x *DeployResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeployResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *DeployResult) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

var File_pkg_protocol_rivet_proto protoreflect.FileDescriptor

const file_pkg_protocol_rivet_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/protocol/rivet.proto\x12\brivet.v1\"\x96\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\x12\x18\n" +
	"\aadapter\x18\a \x01(\tR\aadapter\x12\x14\n" +
	"\x05depth\x18\b \x01(\tR\x05depth\x12'\n" +
	"\x0fcontext_channel\x18\t \x01(\bR\x0econtextChannel\"z\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x14heartbeat_interval_s\x18\x03 \x01(\x05R\x12heartbeatIntervalS\"\xce\x03\n" +
	"\tRunnerMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12'\n" +
	"\x05hello\x18\x02 \x01(\v2\x0f.rivet.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x03 \x01(\v2\x13.rivet.v1.HeartbeatH\x00R\theartbeat\x12,\n" +
	"\x05event\x18\x04 \x01(\v2\x14.rivet.v1.AgentEventH\x00R\x05event\x12;\n" +
	"\n" +
	"transcript\x18\x05 \x01(\v2\x19.rivet.v1.TranscriptChunkH\x00R\n" +
	"transcript\x12'\n" +
	"\x05usage\x18\x06 \x01(\v2\x0f.rivet.v1.UsageH\x00R\x05usage\x12:\n" +
	"\fstage_result\x18\a \x01(\v2\x15.rivet.v1.StageResultH\x00R\vstageResult\x125\n" +
	"\ablocked\x18\b \x01(\v2\x19.rivet.v1.BlockedQuestionH\x00R\ablocked\x12=\n" +
	"\rdeploy_result\x18\t \x01(\v2\x16.rivet.v1.DeployResultH\x00R\fdeployResultB\x06\n" +
	"\x04kind\"$\n" +
	"\x05Hello\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"5\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\actx_pct\x18\x01 \x01(\x05H\x00R\x06ctxPct\x88\x01\x01B\n" +
	"\n" +
	"\b_ctx_pct\"\xbe\x01\n" +
	"\n" +
	"AgentEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04tool\x18\x05 \x01(\tR\x04tool\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x14\n" +
	"\x05files\x18\a \x03(\tR\x05files\x12\x0e\n" +
	"\x02ok\x18\b \x01(\bR\x02ok\"\x8c\x01\n" +
	"\x0fTranscriptChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdeploy_id\x18\x05 \x01(\tR\bdeployId\"\xae\x02\n" +
	"\x05Usage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12 \n" +
	"\ttokens_in\x18\x03 \x01(\x03H\x00R\btokensIn\x88\x01\x01\x12\"\n" +
	"\n" +
	"tokens_out\x18\x04 \x01(\x03H\x01R\ttokensOut\x88\x01\x01\x12\x1e\n" +
	"\bcost_usd\x18\x05 \x01(\x01H\x02R\acostUsd\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x06 \x01(\x05R\tdurationS\x12\x1c\n" +
	"\actx_pct\x18\a \x01(\x05H\x03R\x06ctxPct\x88\x01\x01B\f\n" +
	"\n" +
	"_tokens_inB\r\n" +
	"\v_tokens_outB\v\n" +
	"\t_cost_usdB\n" +
	"\n" +
	"\b_ctx_pct\"\xa9\x02\n" +
	"\vStageResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x1b.rivet.v1.StageResult.StageR\x05stage\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x15\n" +
	"\x06pr_url\x18\x05 \x01(\tR\x05prUrl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vpolicy_hash\x18\a \x01(\tR\n" +
	"policyHash\"O\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CODING\x10\x01\x12\v\n" +
	"\aTESTING\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x03\x12\n" +
	"\n" +
	"\x06FIXING\x10\x04\"e\n" +
	"\x0fBlockedQuestion\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xe5\x02\n" +
	"\bPlaneMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.rivet.v1.AckH\x00R\x03ack\x12.\n" +
	"\x06assign\x18\x03 \x01(\v2\x14.rivet.v1.AssignmentH\x00R\x06assign\x12*\n" +
	"\x06answer\x18\x04 \x01(\v2\x10.rivet.v1.AnswerH\x00R\x06answer\x12.\n" +
	"\x06cancel\x18\x05 \x01(\v2\x14.rivet.v1.CancelTaskH\x00R\x06cancel\x12-\n" +
	"\x05pause\x18\x06 \x01(\v2\x15.rivet.v1.PauseRunnerH\x00R\x05pause\x12-\n" +
	"\x06deploy\x18\a \x01(\v2\x13.rivet.v1.DeployJobH\x00R\x06deploy\x12-\n" +
	"\acontext\x18\b \x01(\v2\x11.rivet.v1.ContextH\x00R\acontextB\x06\n" +
	"\x04kind\"i\n" +
	"\aContext\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"'\n" +
	"\x03Ack\x12 \n" +
	"\facked_msg_id\x18\x01 \x01(\tR\n" +
	"ackedMsgId\"\x84\x04\n" +
	"\n" +
	"Assignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\btask_num\x18\x02 \x01(\x03R\ataskNum\x121\n" +
	"\x05stage\x18\x03 \x01(\x0e2\x1b.rivet.v1.StageResult.StageR\x05stage\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcriteria\x18\x06 \x03(\tR\bcriteria\x12\x12\n" +
	"\x04repo\x18\a \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\b \x01(\tR\x06branch\x12'\n" +
	"\x06checks\x18\t \x03(\v2\x0f.rivet.v1.CheckR\x06checks\x12#\n" +
	"\rextra_context\x18\n" +
	" \x01(\tR\fextraContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\x12\x19\n" +
	"\brepo_url\x18\f \x01(\tR\arepoUrl\x12\x1b\n" +
	"\tgit_token\x18\r \x01(\tR\bgitToken\x12\x1f\n" +
	"\vbase_branch\x18\x0e \x01(\tR\n" +
	"baseBranch\x12\x1f\n" +
	"\vuser_prompt\x18\x0f \x01(\tR\n" +
	"userPrompt\x12(\n" +
	"\x06policy\x18\x10 \x01(\v2\x10.rivet.v1.PolicyR\x06policy\"i\n" +
	"\x06Policy\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12,\n" +
	"\x12human_review_paths\x18\x02 \x03(\tR\x10humanReviewPaths\x12\x1d\n" +
	"\n" +
	"policy_dir\x18\x03 \x01(\tR\tpolicyDir\"-\n" +
	"\x05Check\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\"5\n" +
	"\x06Answer\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"%\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"#\n" +
	"\vPauseRunner\x12\x14\n" +
	"\x05drain\x18\x01 \x01(\bR\x05drain\"\xc6\x02\n" +
	"\tDeployJob\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x19\n" +
	"\benv_name\x18\x02 \x01(\tR\aenvName\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12!\n" +
	"\fprev_version\x18\x05 \x01(\tR\vprevVersion\x12\x1a\n" +
	"\brollback\x18\x06 \x01(\bR\brollback\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"deploy_cmd\x18\b \x01(\tR\tdeployCmd\x12\x1d\n" +
	"\n" +
	"verify_cmd\x18\t \x01(\tR\tverifyCmd\x12\x1d\n" +
	"\n" +
	"verify_url\x18\n" +
	" \x01(\tR\tverifyUrl\x12\x1b\n" +
	"\ttimeout_s\x18\v \x01(\x05R\btimeoutS\"\xe3\x01\n" +
	"\fDeployResult\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x122\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x1c.rivet.v1.DeployResult.StageR\x05stage\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1a\n" +
	"\brollback\x18\x05 \x01(\bR\brollback\"6\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DEPLOY\x10\x01\x12\n" +
	"\n" +
	"\x06VERIFY\x10\x022\x8a\x01\n" +
	"\rRunnerService\x12A\n" +
	"\bRegister\x12\x19.rivet.v1.RegisterRequest\x1a\x1a.rivet.v1.RegisterResponse\x126\n" +
	"\aChannel\x12\x13.rivet.v1.RunnerMsg\x1a\x12.rivet.v1.PlaneMsg(\x010\x01B0Z.github.com/PavluninVladimir/rivet/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_rivet_proto_rawDescOnce sync.Once
	file_pkg_protocol_rivet_proto_rawDescData []byte
)

func file_pkg_protocol_rivet_proto_rawDescGZIP() []byte {
	file_pkg_protocol_rivet_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_rivet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_rivet_proto_rawDesc), len(file_pkg_protocol_rivet_proto_rawDesc)))
	})
	return file_pkg_protocol_rivet_proto_rawDescData
}

var file_pkg_protocol_rivet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_protocol_rivet_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_protocol_rivet_proto_goTypes = []any{
	(StageResult_Stage)(0),   // 0: rivet.v1.StageResult.Stage
	(DeployResult_Stage)(0),  // 1: rivet.v1.DeployResult.Stage
	(*RegisterRequest)(nil),  // 2: rivet.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: rivet.v1.RegisterResponse
	(*RunnerMsg)(nil),        // 4: rivet.v1.RunnerMsg
	(*Hello)(nil),            // 5: rivet.v1.Hello
	(*Heartbeat)(nil),        // 6: rivet.v1.Heartbeat
	(*AgentEvent)(nil),       // 7: rivet.v1.AgentEvent
	(*TranscriptChunk)(nil),  // 8: rivet.v1.TranscriptChunk
	(*Usage)(nil),            // 9: rivet.v1.Usage
	(*StageResult)(nil),      // 10: rivet.v1.StageResult
	(*BlockedQuestion)(nil),  // 11: rivet.v1.BlockedQuestion
	(*PlaneMsg)(nil),         // 12: rivet.v1.PlaneMsg
	(*Context)(nil),          // 13: rivet.v1.Context
	(*Ack)(nil),              // 14: rivet.v1.Ack
	(*Assignment)(nil),       // 15: rivet.v1.Assignment
	(*Policy)(nil),           // 16: rivet.v1.Policy
	(*Check)(nil),            // 17: rivet.v1.Check
	(*Answer)(nil),           // 18: rivet.v1.Answer
	(*CancelTask)(nil),       // 19: rivet.v1.CancelTask
	(*PauseRunner)(nil),      // 20: rivet.v1.PauseRunner
	(*DeployJob)(nil),        // 21: rivet.v1.DeployJob
	(*DeployResult)(nil),     // 22: rivet.v1.DeployResult
}
var file_pkg_protocol_rivet_proto_depIdxs = []int32{
	5,  // 0: rivet.v1.RunnerMsg.hello:type_name -> rivet.v1.Hello
	6,  // 1: rivet.v1.RunnerMsg.heartbeat:type_name -> rivet.v1.Heartbeat
	7,  // 2: rivet.v1.RunnerMsg.event:type_name -> rivet.v1.AgentEvent
	8,  // 3: rivet.v1.RunnerMsg.transcript:type_name -> rivet.v1.TranscriptChunk
	9,  // 4: rivet.v1.RunnerMsg.usage:type_name -> rivet.v1.Usage
	10, // 5: rivet.v1.RunnerMsg.stage_result:type_name -> rivet.v1.StageResult
	11, // 6: rivet.v1.RunnerMsg.blocked:type_name -> rivet.v1.BlockedQuestion
	22, // 7: rivet.v1.RunnerMsg.deploy_result:type_name -> rivet.v1.DeployResult
	0,  // 8: rivet.v1.StageResult.stage:type_name -> rivet.v1.StageResult.Stage
	14, // 9: rivet.v1.PlaneMsg.ack:type_name -> rivet.v1.Ack
	15, // 10: rivet.v1.PlaneMsg.assign:type_name -> rivet.v1.Assignment
	18, // 11: rivet.v1.PlaneMsg.answer:type_name -> rivet.v1.Answer
	19, // 12: rivet.v1.PlaneMsg.cancel:type_name -> rivet.v1.CancelTask
	20, // 13: rivet.v1.PlaneMsg.pause:type_name -> rivet.v1.PauseRunner
	21, // 14: rivet.v1.PlaneMsg.deploy:type_name -> rivet.v1.DeployJob
	13, // 15: rivet.v1.PlaneMsg.context:type_name -> rivet.v1.Context
	0,  // 16: rivet.v1.Assignment.stage:type_name -> rivet.v1.StageResult.Stage
	17, // 17: rivet.v1.Assignment.checks:type_name -> rivet.v1.Check
	16, // 18: rivet.v1.Assignment.policy:type_name -> rivet.v1.Policy
	1,  // 19: rivet.v1.DeployResult.stage:type_name -> rivet.v1.DeployResult.Stage
	2,  // 20: rivet.v1.RunnerService.Register:input_type -> rivet.v1.RegisterRequest
	4,  // 21: rivet.v1.RunnerService.Channel:input_type -> rivet.v1.RunnerMsg
	3,  // 22: rivet.v1.RunnerService.Register:output_type -> rivet.v1.RegisterResponse
	12, // 23: rivet.v1.RunnerService.Channel:output_type -> rivet.v1.PlaneMsg
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_protocol_rivet_proto_init() }
func file_pkg_protocol_rivet_proto_init() {
	if File_pkg_protocol_rivet_proto != nil {
		return
	}
	file_pkg_protocol_rivet_proto_msgTypes[2].OneofWrappers = []any{
		(*RunnerMsg_Hello)(nil),
		(*RunnerMsg_Heartbeat)(nil),
		(*RunnerMsg_Event)(nil),
		(*RunnerMsg_Transcript)(nil),
		(*RunnerMsg_Usage)(nil),
		(*RunnerMsg_StageResult)(nil),
		(*RunnerMsg_Blocked)(nil),
		(*RunnerMsg_DeployResult)(nil),
	}
	file_pkg_protocol_rivet_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_protocol_rivet_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_protocol_rivet_proto_msgTypes[10].OneofWrappers = []any{
		(*PlaneMsg_Ack)(nil),
		(*PlaneMsg_Assign)(nil),
		(*PlaneMsg_Answer)(nil),
		(*PlaneMsg_Cancel)(nil),
		(*PlaneMsg_Pause)(nil),
		(*PlaneMsg_Deploy)(nil),
		(*PlaneMsg_Context)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_rivet_proto_rawDesc), len(file_pkg_protocol_rivet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_rivet_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_rivet_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_rivet_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_rivet_proto_msgTypes,
	}.Build()
	File_pkg_protocol_rivet_proto = out.File
	file_pkg_protocol_rivet_proto_goTypes = nil
	file_pkg_protocol_rivet_proto_depIdxs = nil
}
