// Протокол runner ↔ control plane (см. design и api-contract изменения
// define-rivet-architecture). Соединение всегда исходящее от runner'а.
// Доставка at-least-once: каждое сообщение несёт msg_id, приём подтверждается
// Ack, дедупликация на стороне получателя.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/protocol/rivet.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageResult_Stage int32

const (
	StageResult_STAGE_UNSPECIFIED StageResult_Stage = 0
	StageResult_CODING            StageResult_Stage = 1 // реализация завершена (ok) или невосстановимая ошибка (!ok)
	StageResult_TESTING           StageResult_Stage = 2 // проверки прошли/упали
	StageResult_REVIEW            StageResult_Stage = 3 // вердикт независимого ревьюера
	StageResult_FIXING            StageResult_Stage = 4 // исправление готово
)

// Enum value maps for StageResult_Stage.
var (
	StageResult_Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "CODING",
		2: "TESTING",
		3: "REVIEW",
		4: "FIXING",
	}
	StageResult_Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"CODING":            1,
		"TESTING":           2,
		"REVIEW":            3,
		"FIXING":            4,
	}
)

func (x StageResult_Stage) Enum() *StageResult_Stage {
	p := new(StageResult_Stage)
	*p = x
	return p
}

func (x StageResult_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageResult_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_rivet_proto_enumTypes[0].Descriptor()
}

func (StageResult_Stage) Type() protoreflect.EnumType {
	return &file_pkg_protocol_rivet_proto_enumTypes[0]
}

func (x StageResult_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageResult_Stage.Descriptor instead.
func (StageResult_Stage) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{8, 0}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunnerId        string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Agent           string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Host            string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Capabilities    []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Несовместимая версия протокола — понятная ошибка, не разрыв соединения.
	Accepted           bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message            string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalS int32  `protobuf:"varint,3,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalS() int32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

type RunnerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // uuid, база дедупликации и Ack
	// Types that are valid to be assigned to Kind:
	//
	//	*RunnerMsg_Hello
	//	*RunnerMsg_Heartbeat
	//	*RunnerMsg_Event
	//	*RunnerMsg_Transcript
	//	*RunnerMsg_Usage
	//	*RunnerMsg_StageResult
	//	*RunnerMsg_Blocked
	Kind          isRunnerMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerMsg) Reset() {
	*x = RunnerMsg{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerMsg) ProtoMessage() {}

func (x *RunnerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerMsg.ProtoReflect.Descriptor instead.
func (*RunnerMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{2}
}

func (x *RunnerMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RunnerMsg) GetKind() isRunnerMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunnerMsg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *RunnerMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunnerMsg) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunnerMsg) GetTranscript() *TranscriptChunk {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *RunnerMsg) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *RunnerMsg) GetStageResult() *StageResult {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_StageResult); ok {
			return x.StageResult
		}
	}
	return nil
}

func (x *RunnerMsg) GetBlocked() *BlockedQuestion {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMsg_Blocked); ok {
			return x.Blocked
		}
	}
	return nil
}

type isRunnerMsg_Kind interface {
	isRunnerMsg_Kind()
}

type RunnerMsg_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type RunnerMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type RunnerMsg_Event struct {
	Event *AgentEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type RunnerMsg_Transcript struct {
	Transcript *TranscriptChunk `protobuf:"bytes,5,opt,name=transcript,proto3,oneof"`
}

type RunnerMsg_Usage struct {
	Usage *Usage `protobuf:"bytes,6,opt,name=usage,proto3,oneof"`
}

type RunnerMsg_StageResult struct {
	StageResult *StageResult `protobuf:"bytes,7,opt,name=stage_result,json=stageResult,proto3,oneof"`
}

type RunnerMsg_Blocked struct {
	Blocked *BlockedQuestion `protobuf:"bytes,8,opt,name=blocked,proto3,oneof"`
}

func (*RunnerMsg_Hello) isRunnerMsg_Kind() {}

func (*RunnerMsg_Heartbeat) isRunnerMsg_Kind() {}

func (*RunnerMsg_Event) isRunnerMsg_Kind() {}

func (*RunnerMsg_Transcript) isRunnerMsg_Kind() {}

func (*RunnerMsg_Usage) isRunnerMsg_Kind() {}

func (*RunnerMsg_StageResult) isRunnerMsg_Kind() {}

func (*RunnerMsg_Blocked) isRunnerMsg_Kind() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отсутствие поля = заполненность контекста неизвестна (агент не отчитался).
	CtxPct        *int32 `protobuf:"varint,1,opt,name=ctx_pct,json=ctxPct,proto3,oneof" json:"ctx_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetCtxPct() int32 {
	if x != nil && x.CtxPct != nil {
		return *x.CtxPct
	}
	return 0
}

// AgentEvent — шаг агента для live-наблюдения (session.step).
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{5}
}

func (x *AgentEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscriptChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptChunk) Reset() {
	*x = TranscriptChunk{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptChunk) ProtoMessage() {}

func (x *TranscriptChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptChunk.ProtoReflect.Descriptor instead.
func (*TranscriptChunk) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{6}
}

func (x *TranscriptChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TranscriptChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TranscriptChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Usage — отчёт о расходе за стадию. Отсутствие optional-поля означает
// «данных нет» (агент не отчитался маркером USAGE:), а не ноль.
type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TokensIn      *int64                 `protobuf:"varint,3,opt,name=tokens_in,json=tokensIn,proto3,oneof" json:"tokens_in,omitempty"`
	TokensOut     *int64                 `protobuf:"varint,4,opt,name=tokens_out,json=tokensOut,proto3,oneof" json:"tokens_out,omitempty"`
	CostUsd       *float64               `protobuf:"fixed64,5,opt,name=cost_usd,json=costUsd,proto3,oneof" json:"cost_usd,omitempty"`
	DurationS     int32                  `protobuf:"varint,6,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	CtxPct        *int32                 `protobuf:"varint,7,opt,name=ctx_pct,json=ctxPct,proto3,oneof" json:"ctx_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Usage) GetTokensIn() int64 {
	if x != nil && x.TokensIn != nil {
		return *x.TokensIn
	}
	return 0
}

func (x *Usage) GetTokensOut() int64 {
	if x != nil && x.TokensOut != nil {
		return *x.TokensOut
	}
	return 0
}

func (x *Usage) GetCostUsd() float64 {
	if x != nil && x.CostUsd != nil {
		return *x.CostUsd
	}
	return 0
}

func (x *Usage) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *Usage) GetCtxPct() int32 {
	if x != nil && x.CtxPct != nil {
		return *x.CtxPct
	}
	return 0
}

// StageResult — детерминированный итог этапа конвейера.
type StageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         StageResult_Stage      `protobuf:"varint,2,opt,name=stage,proto3,enum=rivet.v1.StageResult_Stage" json:"stage,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`            // вывод тестов, вердикт review, url PR
	PrUrl         string                 `protobuf:"bytes,5,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"` // для stage=CODING при создании PR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageResult) Reset() {
	*x = StageResult{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageResult) ProtoMessage() {}

func (x *StageResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageResult.ProtoReflect.Descriptor instead.
func (*StageResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{8}
}

func (x *StageResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageResult) GetStage() StageResult_Stage {
	if x != nil {
		return x.Stage
	}
	return StageResult_STAGE_UNSPECIFIED
}

func (x *StageResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StageResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *StageResult) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

// BlockedQuestion — агент не может продолжить без человека.
type BlockedQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedQuestion) Reset() {
	*x = BlockedQuestion{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedQuestion) ProtoMessage() {}

func (x *BlockedQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedQuestion.ProtoReflect.Descriptor instead.
func (*BlockedQuestion) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedQuestion) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BlockedQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type PlaneMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PlaneMsg_Ack
	//	*PlaneMsg_Assign
	//	*PlaneMsg_Answer
	//	*PlaneMsg_Cancel
	//	*PlaneMsg_Pause
	Kind          isPlaneMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaneMsg) Reset() {
	*x = PlaneMsg{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneMsg) ProtoMessage() {}

func (x *PlaneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneMsg.ProtoReflect.Descriptor instead.
func (*PlaneMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{10}
}

func (x *PlaneMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PlaneMsg) GetKind() isPlaneMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PlaneMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *PlaneMsg) GetAssign() *Assignment {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *PlaneMsg) GetAnswer() *Answer {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *PlaneMsg) GetCancel() *CancelTask {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *PlaneMsg) GetPause() *PauseRunner {
	if x != nil {
		if x, ok := x.Kind.(*PlaneMsg_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

type isPlaneMsg_Kind interface {
	isPlaneMsg_Kind()
}

type PlaneMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type PlaneMsg_Assign struct {
	Assign *Assignment `protobuf:"bytes,3,opt,name=assign,proto3,oneof"`
}

type PlaneMsg_Answer struct {
	Answer *Answer `protobuf:"bytes,4,opt,name=answer,proto3,oneof"`
}

type PlaneMsg_Cancel struct {
	Cancel *CancelTask `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type PlaneMsg_Pause struct {
	Pause *PauseRunner `protobuf:"bytes,6,opt,name=pause,proto3,oneof"`
}

func (*PlaneMsg_Ack) isPlaneMsg_Kind() {}

func (*PlaneMsg_Assign) isPlaneMsg_Kind() {}

func (*PlaneMsg_Answer) isPlaneMsg_Kind() {}

func (*PlaneMsg_Cancel) isPlaneMsg_Kind() {}

func (*PlaneMsg_Pause) isPlaneMsg_Kind() {}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedMsgId    string                 `protobuf:"bytes,1,opt,name=acked_msg_id,json=ackedMsgId,proto3" json:"acked_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetAckedMsgId() string {
	if x != nil {
		return x.AckedMsgId
	}
	return ""
}

// Assignment — задача этапу runner'а: кодирование, тесты, review или фикс.
type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNum       int64                  `protobuf:"varint,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	Stage         StageResult_Stage      `protobuf:"varint,3,opt,name=stage,proto3,enum=rivet.v1.StageResult_Stage" json:"stage,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Criteria      []string               `protobuf:"bytes,6,rep,name=criteria,proto3" json:"criteria,omitempty"`
	Repo          string                 `protobuf:"bytes,7,opt,name=repo,proto3" json:"repo,omitempty"`     // owner/name
	Branch        string                 `protobuf:"bytes,8,opt,name=branch,proto3" json:"branch,omitempty"` // agent/task-<num>
	Checks        []*Check               `protobuf:"bytes,9,rep,name=checks,proto3" json:"checks,omitempty"`
	ExtraContext  string                 `protobuf:"bytes,10,opt,name=extra_context,json=extraContext,proto3" json:"extra_context,omitempty"` // замечания review при FIXING, diff при REVIEW и т.п.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{12}
}

func (x *Assignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Assignment) GetTaskNum() int64 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *Assignment) GetStage() StageResult_Stage {
	if x != nil {
		return x.Stage
	}
	return StageResult_STAGE_UNSPECIFIED
}

func (x *Assignment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assignment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Assignment) GetCriteria() []string {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *Assignment) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Assignment) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Assignment) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *Assignment) GetExtraContext() string {
	if x != nil {
		return x.ExtraContext
	}
	return ""
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{13}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{14}
}

func (x *Answer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Answer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PauseRunner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drain         bool                   `protobuf:"varint,1,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunner) Reset() {
	*x = PauseRunner{}
	mi := &file_pkg_protocol_rivet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunner) ProtoMessage() {}

func (x *PauseRunner) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_rivet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunner.ProtoReflect.Descriptor instead.
func (*PauseRunner) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_rivet_proto_rawDescGZIP(), []int{16}
}

func (x *PauseRunner) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

var File_pkg_protocol_rivet_proto protoreflect.FileDescriptor

const file_pkg_protocol_rivet_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/protocol/rivet.proto\x12\brivet.v1\"\xbd\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\"z\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x14heartbeat_interval_s\x18\x03 \x01(\x05R\x12heartbeatIntervalS\"\x8f\x03\n" +
	"\tRunnerMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12'\n" +
	"\x05hello\x18\x02 \x01(\v2\x0f.rivet.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x03 \x01(\v2\x13.rivet.v1.HeartbeatH\x00R\theartbeat\x12,\n" +
	"\x05event\x18\x04 \x01(\v2\x14.rivet.v1.AgentEventH\x00R\x05event\x12;\n" +
	"\n" +
	"transcript\x18\x05 \x01(\v2\x19.rivet.v1.TranscriptChunkH\x00R\n" +
	"transcript\x12'\n" +
	"\x05usage\x18\x06 \x01(\v2\x0f.rivet.v1.UsageH\x00R\x05usage\x12:\n" +
	"\fstage_result\x18\a \x01(\v2\x15.rivet.v1.StageResultH\x00R\vstageResult\x125\n" +
	"\ablocked\x18\b \x01(\v2\x19.rivet.v1.BlockedQuestionH\x00R\ablockedB\x06\n" +
	"\x04kind\"$\n" +
	"\x05Hello\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"5\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\actx_pct\x18\x01 \x01(\x05H\x00R\x06ctxPct\x88\x01\x01B\n" +
	"\n" +
	"\b_ctx_pct\"9\n" +
	"\n" +
	"AgentEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"P\n" +
	"\x0fTranscriptChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x8f\x02\n" +
	"\x05Usage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12 \n" +
	"\ttokens_in\x18\x03 \x01(\x03H\x00R\btokensIn\x88\x01\x01\x12\"\n" +
	"\n" +
	"tokens_out\x18\x04 \x01(\x03H\x01R\ttokensOut\x88\x01\x01\x12\x1e\n" +
	"\bcost_usd\x18\x05 \x01(\x01H\x02R\acostUsd\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x06 \x01(\x05R\tdurationS\x12\x1c\n" +
	"\actx_pct\x18\a \x01(\x05H\x03R\x06ctxPct\x88\x01\x01B\f\n" +
	"\n" +
	"_tokens_inB\r\n" +
	"\v_tokens_outB\v\n" +
	"\t_cost_usdB\n" +
	"\n" +
	"\b_ctx_pct\"\xe9\x01\n" +
	"\vStageResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x1b.rivet.v1.StageResult.StageR\x05stage\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x15\n" +
	"\x06pr_url\x18\x05 \x01(\tR\x05prUrl\"O\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CODING\x10\x01\x12\v\n" +
	"\aTESTING\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x03\x12\n" +
	"\n" +
	"\x06FIXING\x10\x04\"F\n" +
	"\x0fBlockedQuestion\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"\x87\x02\n" +
	"\bPlaneMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.rivet.v1.AckH\x00R\x03ack\x12.\n" +
	"\x06assign\x18\x03 \x01(\v2\x14.rivet.v1.AssignmentH\x00R\x06assign\x12*\n" +
	"\x06answer\x18\x04 \x01(\v2\x10.rivet.v1.AnswerH\x00R\x06answer\x12.\n" +
	"\x06cancel\x18\x05 \x01(\v2\x14.rivet.v1.CancelTaskH\x00R\x06cancel\x12-\n" +
	"\x05pause\x18\x06 \x01(\v2\x15.rivet.v1.PauseRunnerH\x00R\x05pauseB\x06\n" +
	"\x04kind\"'\n" +
	"\x03Ack\x12 \n" +
	"\facked_msg_id\x18\x01 \x01(\tR\n" +
	"ackedMsgId\"\xc1\x02\n" +
	"\n" +
	"Assignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\btask_num\x18\x02 \x01(\x03R\ataskNum\x121\n" +
	"\x05stage\x18\x03 \x01(\x0e2\x1b.rivet.v1.StageResult.StageR\x05stage\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcriteria\x18\x06 \x03(\tR\bcriteria\x12\x12\n" +
	"\x04repo\x18\a \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\b \x01(\tR\x06branch\x12'\n" +
	"\x06checks\x18\t \x03(\v2\x0f.rivet.v1.CheckR\x06checks\x12#\n" +
	"\rextra_context\x18\n" +
	" \x01(\tR\fextraContext\"-\n" +
	"\x05Check\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\"5\n" +
	"\x06Answer\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"%\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"#\n" +
	"\vPauseRunner\x12\x14\n" +
	"\x05drain\x18\x01 \x01(\bR\x05drain2\x8a\x01\n" +
	"\rRunnerService\x12A\n" +
	"\bRegister\x12\x19.rivet.v1.RegisterRequest\x1a\x1a.rivet.v1.RegisterResponse\x126\n" +
	"\aChannel\x12\x13.rivet.v1.RunnerMsg\x1a\x12.rivet.v1.PlaneMsg(\x010\x01B0Z.github.com/PavluninVladimir/rivet/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_rivet_proto_rawDescOnce sync.Once
	file_pkg_protocol_rivet_proto_rawDescData []byte
)

func file_pkg_protocol_rivet_proto_rawDescGZIP() []byte {
	file_pkg_protocol_rivet_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_rivet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_rivet_proto_rawDesc), len(file_pkg_protocol_rivet_proto_rawDesc)))
	})
	return file_pkg_protocol_rivet_proto_rawDescData
}

var file_pkg_protocol_rivet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_rivet_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_protocol_rivet_proto_goTypes = []any{
	(StageResult_Stage)(0),   // 0: rivet.v1.StageResult.Stage
	(*RegisterRequest)(nil),  // 1: rivet.v1.RegisterRequest
	(*RegisterResponse)(nil), // 2: rivet.v1.RegisterResponse
	(*RunnerMsg)(nil),        // 3: rivet.v1.RunnerMsg
	(*Hello)(nil),            // 4: rivet.v1.Hello
	(*Heartbeat)(nil),        // 5: rivet.v1.Heartbeat
	(*AgentEvent)(nil),       // 6: rivet.v1.AgentEvent
	(*TranscriptChunk)(nil),  // 7: rivet.v1.TranscriptChunk
	(*Usage)(nil),            // 8: rivet.v1.Usage
	(*StageResult)(nil),      // 9: rivet.v1.StageResult
	(*BlockedQuestion)(nil),  // 10: rivet.v1.BlockedQuestion
	(*PlaneMsg)(nil),         // 11: rivet.v1.PlaneMsg
	(*Ack)(nil),              // 12: rivet.v1.Ack
	(*Assignment)(nil),       // 13: rivet.v1.Assignment
	(*Check)(nil),            // 14: rivet.v1.Check
	(*Answer)(nil),           // 15: rivet.v1.Answer
	(*CancelTask)(nil),       // 16: rivet.v1.CancelTask
	(*PauseRunner)(nil),      // 17: rivet.v1.PauseRunner
}
var file_pkg_protocol_rivet_proto_depIdxs = []int32{
	4,  // 0: rivet.v1.RunnerMsg.hello:type_name -> rivet.v1.Hello
	5,  // 1: rivet.v1.RunnerMsg.heartbeat:type_name -> rivet.v1.Heartbeat
	6,  // 2: rivet.v1.RunnerMsg.event:type_name -> rivet.v1.AgentEvent
	7,  // 3: rivet.v1.RunnerMsg.transcript:type_name -> rivet.v1.TranscriptChunk
	8,  // 4: rivet.v1.RunnerMsg.usage:type_name -> rivet.v1.Usage
	9,  // 5: rivet.v1.RunnerMsg.stage_result:type_name -> rivet.v1.StageResult
	10, // 6: rivet.v1.RunnerMsg.blocked:type_name -> rivet.v1.BlockedQuestion
	0,  // 7: rivet.v1.StageResult.stage:type_name -> rivet.v1.StageResult.Stage
	12, // 8: rivet.v1.PlaneMsg.ack:type_name -> rivet.v1.Ack
	13, // 9: rivet.v1.PlaneMsg.assign:type_name -> rivet.v1.Assignment
	15, // 10: rivet.v1.PlaneMsg.answer:type_name -> rivet.v1.Answer
	16, // 11: rivet.v1.PlaneMsg.cancel:type_name -> rivet.v1.CancelTask
	17, // 12: rivet.v1.PlaneMsg.pause:type_name -> rivet.v1.PauseRunner
	0,  // 13: rivet.v1.Assignment.stage:type_name -> rivet.v1.StageResult.Stage
	14, // 14: rivet.v1.Assignment.checks:type_name -> rivet.v1.Check
	1,  // 15: rivet.v1.RunnerService.Register:input_type -> rivet.v1.RegisterRequest
	3,  // 16: rivet.v1.RunnerService.Channel:input_type -> rivet.v1.RunnerMsg
	2,  // 17: rivet.v1.RunnerService.Register:output_type -> rivet.v1.RegisterResponse
	11, // 18: rivet.v1.RunnerService.Channel:output_type -> rivet.v1.PlaneMsg
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_protocol_rivet_proto_init() }
func file_pkg_protocol_rivet_proto_init() {
	if File_pkg_protocol_rivet_proto != nil {
		return
	}
	file_pkg_protocol_rivet_proto_msgTypes[2].OneofWrappers = []any{
		(*RunnerMsg_Hello)(nil),
		(*RunnerMsg_Heartbeat)(nil),
		(*RunnerMsg_Event)(nil),
		(*RunnerMsg_Transcript)(nil),
		(*RunnerMsg_Usage)(nil),
		(*RunnerMsg_StageResult)(nil),
		(*RunnerMsg_Blocked)(nil),
	}
	file_pkg_protocol_rivet_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_protocol_rivet_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_protocol_rivet_proto_msgTypes[10].OneofWrappers = []any{
		(*PlaneMsg_Ack)(nil),
		(*PlaneMsg_Assign)(nil),
		(*PlaneMsg_Answer)(nil),
		(*PlaneMsg_Cancel)(nil),
		(*PlaneMsg_Pause)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_rivet_proto_rawDesc), len(file_pkg_protocol_rivet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_rivet_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_rivet_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_rivet_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_rivet_proto_msgTypes,
	}.Build()
	File_pkg_protocol_rivet_proto = out.File
	file_pkg_protocol_rivet_proto_goTypes = nil
	file_pkg_protocol_rivet_proto_depIdxs = nil
}
